echo_run: 0
genome_path: data/fasta/Homo_sapiens.GRCh37.GATK.illumina # reference in FASTA

file_exts:
  fasta: .fasta
  fasta_idx:
    - .fasta.fai # faidx index file
    - .fasta.bwt # bwa v0.6.x
    - .fasta.amb # index files
    - .fasta.ann #
    - .fasta.pac #
    - .fasta.sa  #
  bam: .bam
  bam_idx: .bai

samples: samples.csv # list of tumor-normal sample pairs

sv_callers:
  manta:
    threads: 32
    memory: 10240 #MB
    outdir: manta_out

  delly:
    threads: 2
    memory: 3072 #MB
    outdir: delly_out

  lumpy:
    threads: 1
    memory: 10240 #MB
    outdir: lumpy_out

  gridss:
    threads: 16
    memory: 63488 #MB
    outdir: gridss_out

