ref_genome: Homo_sapiens.GRCh37.GATK.illumina

file_exts:
  fasta:  .fasta
  fai:    .fasta.fai
  bam:    .bam
  bai:    .bai

samples: samples.tsv

outdirs:
  manta:  manta_out
  delly:  delly_out
  lumpy:  lumpy_out
  gridss: gridss_out
