echo_run: 0 # run sv callers [0] or vanilla jobs [1]

# filepath to the reference genome in FASTA (excl. file suffix)
genome_path: data/fasta/Homo_sapiens.GRCh37.GATK.illumina

file_exts:
  fasta: .fasta
  fasta_idx:
    - .fasta.fai # faidx index file
    - .fasta.bwt # bwa v0.6.x
    - .fasta.amb # index files
    - .fasta.ann #
    - .fasta.pac #
    - .fasta.sa  #
  bam: .bam
  bam_idx: .bai

samples: samples.csv # list of tumor-normal sample pairs (*.bam files)

sv_callers:
  manta:
    threads: 32
    memory: 10240 #MB
    outdir: manta_out # relative to SAMPLE_DIR (see samples.csv)

  delly:
    threads: 2
    memory: 3072 #MB
    outdir: delly_out
    sv_types:
        - BND
        - DEL
        - DUP
        - INS
        - INV

  lumpy:
    threads: 1
    memory: 10240 #MB
    outdir: lumpy_out

  gridss:
    threads: 16
    memory: 63488 #MB
    outdir: gridss_out
