ref_genome: Homo_sapiens.GRCh37.GATK.illumina

file_exts:
  fasta:  .fasta
  fai:    .fasta.fai
  bam:    .bam
  bai:    .bam.bai

samples: samples.csv

sv_callers:
  manta:
    threads: 1
    memory: 100 #MB
    outdir: manta_out

  delly:
    threads: 1
    memory: 100 #MB
    outdir: delly_out

  lumpy:
    threads: 1
    memory: 100 #MB
    outdir: lumpy_out

  gridss:
    threads: 1
    memory: 100 #MB
    outdir: gridss_out
