ref_genome: data/fasta/Homo_sapiens.GRCh37.GATK.illumina

file_exts:
  fasta:  .fasta
  fasta_idx:
    - .fasta.fai # faidx index file
    - .fasta.bwt # bwa v0.6.x
    - .fasta.amb # index files
    - .fasta.ann #
    - .fasta.pac #
    - .fasta.sa  #
  bam:  .bam
  bam_idx:  .bam.bai

samples: samples.csv # list of tumor-normal sample pairs

sv_callers:
  manta:
    threads: 1
    memory: 100 #MB
    outdir: manta_out

  delly:
    threads: 1
    memory: 100 #MB
    outdir: delly_out

  lumpy:
    threads: 1
    memory: 100 #MB
    outdir: lumpy_out

  gridss:
    threads: 1
    memory: 100 #MB
    outdir: gridss_out
