ref_genome: Homo_sapiens.GRCh37.GATK.illumina

file_exts:
  fasta:  .fasta
  fai:    .fasta.fai
  bam:    .bam
  bai:    .bam.bai

samples: samples.csv

sv_callers:
  manta:
    outdir: manta_out
  delly:
    outdir: delly_out
  lumpy:
    outdir: lumpy_out
  gridss:
    outdir: gridss_out

